languageCode = "pt"
languageName = "Português"
languageDirection = "ltr"
weight = 2

title = "ριтєя мαяχ"

[params]
  dateFormat = "2 January 2006"
  description = "Once I was born and now I'm alive!"

[params.author]
  name = "ριтєя мαяχ"
  image = "img/pitermarx.jpg"
  headline = "Once I was born and now I'm alive!"
  links = [
     { goodreads = "https://goodreads.com/pitermarx/" },
     { flickr = "https://www.flickr.com/photos/pitermarx/" },
     { github = "https://github.com/pitermarx" },
  #   { gitlab = "https://gitlab.com/pitermarx" },
  #   { instagram = "https://instagram.com/pitermarx" },
     { keybase = "https://keybase.io/pitermarx" },
     { lastfm = "https://www.last.fm/user/PedroMarques" },
     { linkedin = "https://linkedin.com/in/pitermarx" },
     { mastodon = "https://masto.pt/@pitermarx" },
     { soundcloud = "https://soundcloud.com/pitermarx" },
     { stack-overflow = "https://stackoverflow.com/users/2633434/pitermarx" },
     { x-twitter = "https://twitter.com/pitermarx" }
  ]

